import type { ToxicLink } from "./toxicLinks";

/**
 * Generates a Google Disavow file from toxic backlinks.
 *
 * Format:
 * - `domain:example.com` for domain-level disavows
 * - `# Comment lines` for metadata
 * - One entry per unique domain (deduped)
 *
 * @see https://developers.google.com/search/docs/crawling-indexing/ask-google-to-reconsider
 */
export function generateDisavowFile(
  toxicLinks: ToxicLink[],
  options?: { comment?: string },
): string {
  const lines: string[] = [];

  lines.push("# Disavow file generated by SeoTool.im");
  lines.push(`# Generated: ${new Date().toISOString().slice(0, 10)}`);
  if (options?.comment) {
    lines.push(`# ${options.comment}`);
  }
  lines.push(`# Toxic links found: ${toxicLinks.length}`);
  lines.push("");

  const uniqueDomains = new Set<string>();
  for (const link of toxicLinks) {
    const domain = normalizeDomain(link.domainFrom);
    if (domain) {
      uniqueDomains.add(domain);
    }
  }

  const sortedDomains = [...uniqueDomains].toSorted();
  for (const domain of sortedDomains) {
    lines.push(`domain:${domain}`);
  }

  return lines.join("\n") + "\n";
}

function normalizeDomain(domain: string): string | null {
  let cleaned = domain.toLowerCase().trim();
  if (cleaned.startsWith("www.")) {
    cleaned = cleaned.slice(4);
  }
  if (!cleaned || cleaned.includes(" ") || cleaned.includes("/")) {
    return null;
  }
  return cleaned;
}
