import { getDatabaseProvider } from "./provider";
import * as sqliteApp from "./app.schema";
import * as sqliteAudit from "./audit.schema";
import * as sqliteSam from "./sam.schema";
import * as sqliteAuth from "./better-auth-schema";
import * as sqliteBilling from "./billing.schema";
import * as sqliteQuota from "./quota.schema";
import * as sqliteGsc from "./gsc.schema";
import * as sqliteGa4 from "./ga4.schema";
import * as sqliteReports from "./reports.schema";
import * as sqliteContentIntelligence from "./content-intelligence.schema";
import * as sqliteReddit from "./reddit-attribution.schema";
import * as sqliteTelemetry from "./telemetry.schema";
import * as pgApp from "./pg/app.schema";
import * as pgAudit from "./pg/audit.schema";
import * as pgSam from "./pg/sam.schema";
import * as pgAuth from "./pg/better-auth-schema";
import * as pgBilling from "./pg/billing.schema";
import * as pgQuota from "./pg/quota.schema";
import * as pgGsc from "./pg/gsc.schema";
import * as pgGa4 from "./pg/ga4.schema";
import * as pgReports from "./pg/reports.schema";
import * as pgContentIntelligence from "./pg/content-intelligence.schema";
import * as pgReddit from "./pg/reddit-attribution.schema";
import * as pgTelemetry from "./pg/telemetry.schema";
import * as sqliteContentStrategy from "./content-strategy.schema";
import * as pgContentStrategy from "./pg/content-strategy.schema";
import * as sqliteAlerts from "./alerts.schema";
import * as pgAlerts from "./pg/alerts.schema";
import * as sqliteSerpSnapshots from "./serp-snapshots.schema";
import * as pgSerpSnapshots from "./pg/serp-snapshots.schema";
import * as sqliteSerpVolatility from "./serp-volatility.schema";
import * as pgSerpVolatility from "./pg/serp-volatility.schema";
import * as sqliteApiKeys from "./api-keys.schema";
import * as pgApiKeys from "./pg/api-keys.schema";
import * as sqliteAdmin from "./admin.schema";
import * as pgAdmin from "./pg/admin.schema";
import * as sqliteNotifications from "./notifications.schema";
import * as pgNotifications from "./pg/notifications.schema";

// Canonical schema barrel. Repositories import their tables from here and the
// provider-aware `db` from "@/db", so each repository is written ONCE for both
// backends.
//
// The TYPE identity is the SQLite definitions; the runtime VALUES are whichever
// provider is active. `schema-parity.test.ts` asserts the two dialect schemas
// are structurally interchangeable (same tables/columns/nullability/PKs/unique
// indexes), which is what makes the single cast below sound. The Postgres
// schema is the one structural artifact NOT regenerated by `db:generate`, so the
// parity test is its drift guard.
type AppSchema = typeof sqliteApp &
  typeof sqliteAudit &
  typeof sqliteSam &
  typeof sqliteAuth &
  typeof sqliteBilling &
  typeof sqliteQuota &
  typeof sqliteGsc &
  typeof sqliteGa4 &
  typeof sqliteReports &
  typeof sqliteContentIntelligence &
  typeof sqliteReddit &
  typeof sqliteTelemetry &
  typeof sqliteContentStrategy &
  typeof sqliteAlerts &
  typeof sqliteSerpSnapshots &
  typeof sqliteSerpVolatility &
  typeof sqliteApiKeys &
  typeof sqliteNotifications &
  typeof sqliteAdmin;

const runtimeSchema =
  getDatabaseProvider() === "postgres"
    ? {
        ...pgApp,
        ...pgAudit,
        ...pgSam,
        ...pgAuth,
        ...pgBilling,
        ...pgQuota,
        ...pgGsc,
        ...pgGa4,
        ...pgReports,
        ...pgContentIntelligence,
        ...pgReddit,
        ...pgTelemetry,
        ...pgContentStrategy,
        ...pgAlerts,
        ...pgSerpSnapshots,
        ...pgSerpVolatility,
        ...pgApiKeys,
        ...pgNotifications,
        ...pgAdmin,
      }
    : {
        ...sqliteApp,
        ...sqliteAudit,
        ...sqliteSam,
        ...sqliteAuth,
        ...sqliteBilling,
        ...sqliteQuota,
        ...sqliteGsc,
        ...sqliteGa4,
        ...sqliteReports,
        ...sqliteContentIntelligence,
        ...sqliteReddit,
        ...sqliteTelemetry,
        ...sqliteContentStrategy,
        ...sqliteAlerts,
        ...sqliteSerpSnapshots,
        ...sqliteSerpVolatility,
        ...sqliteApiKeys,
        ...sqliteNotifications,
        ...sqliteAdmin,
      };

// oxlint-disable-next-line typescript/no-unsafe-type-assertion -- guarded by schema-parity.test.ts
const schema = runtimeSchema as unknown as AppSchema;

export const {
  userOnboardingAnswers,
  projects,
  savedKeywords,
  savedKeywordTags,
  savedKeywordTagAssignments,
  keywordMetrics,
  rankTrackingConfigs,
  rankTrackingKeywords,
  rankCheckRuns,
  rankSnapshots,
  organizationActivationState,
  projectActivationState,
  backlinkSnapshots,
  audits,
  auditPages,
  auditLinks,
  auditIssues,
  auditLighthouseResults,
  samSessions,
  samProjectMemory,
  user,
  session,
  account,
  verification,
  organization,
  member,
  invitation,
  billingCustomerStatus,
  usageQuota,
  subscription,
  gscConnections,
  ga4Connections,
  reports,
  reportSections,
  reportSnapshots,
  reportDeliveries,
  contentScores,
  pageEntities,
  redditAttributions,
  telemetryState,
  topicClusters,
  contentBriefs,
  alertRules,
  serpSnapshots,
  serpVolatilitySnapshots,
  apiKeys,
  notifications,
  appSettings,
  planConfig,
  cmsPosts,
  cmsPages,
  paypalWebhookEvents,
  gmbGridConfigs,
  gmbGridRuns,
  gmbGridSnapshots,
} = schema;
