import { useState } from "react";
import { Download, AlertTriangle } from "lucide-react";
import type { BacklinksRow } from "./backlinksPageTypes";
import { formatDecimal, formatNumber } from "./backlinksPageUtils";
import { downloadDisavowFile } from "./disavowExport";

type ToxicData = {
  links: BacklinksRow[];
  summary: {
    totalToxic: number;
    totalAnalyzed: number;
    toxicPercentage: number;
    topToxicDomains: { domain: string; count: number; avgSpamScore: number }[];
  };
};

export function ToxicLinksTable({
  rows,
  target,
}: {
  rows: BacklinksRow[];
  target: string;
}) {
  const [showDetails, setShowDetails] = useState(false);

  if (rows.length === 0) {
    return (
      <div className="py-8 text-center text-base-content/60">
        <AlertTriangle className="mx-auto mb-2 size-8 text-success" />
        <p>No toxic backlinks detected.</p>
        <p className="text-xs mt-1">
          All analyzed backlinks have a spam score below the threshold.
        </p>
      </div>
    );
  }

  const handleDisavow = () => {
    const domains = new Set<string>();
    for (const row of rows) {
      if (row.domainFrom) {
        const domain = row.domainFrom.toLowerCase().replace(/^www\./, "");
        domains.add(domain);
      }
    }
    const lines = [
      "# Disavow file generated by SeoTool.im",
      `# Generated: ${new Date().toISOString().slice(0, 10)}`,
      `# Toxic links: ${rows.length}`,
      "",
      ...[...domains].sort().map((d) => `domain:${d}`),
    ];
    downloadDisavowFile(lines.join("\n") + "\n", target);
  };

  return (
    <div className="space-y-4">
      <div className="flex flex-wrap items-center gap-4">
        <div className="stats stats-horizontal border border-base-300">
          <div className="stat px-4 py-2">
            <div className="stat-title text-xs">Toxic Links</div>
            <div className="stat-value text-lg text-error">
              {formatNumber(rows.length)}
            </div>
          </div>
          <div className="stat px-4 py-2">
            <div className="stat-title text-xs">Unique Domains</div>
            <div className="stat-value text-lg">
              {formatNumber(
                new Set(rows.map((r) => r.domainFrom).filter(Boolean)).size,
              )}
            </div>
          </div>
        </div>

        <button
          type="button"
          className="btn btn-sm btn-error btn-outline gap-1.5"
          onClick={handleDisavow}
        >
          <Download className="size-3.5" />
          Download Disavow File
        </button>

        <button
          type="button"
          className="btn btn-ghost btn-sm"
          onClick={() => setShowDetails(!showDetails)}
        >
          {showDetails ? "Hide" : "Show"} All Links
        </button>
      </div>

      {showDetails ? (
        <div className="overflow-x-auto">
          <table className="table table-sm">
            <thead>
              <tr>
                <th>Domain</th>
                <th>Spam Score</th>
                <th>Rank</th>
                <th>Source URL</th>
              </tr>
            </thead>
            <tbody>
              {rows.map((row, i) => (
                <tr
                  key={`${row.domainFrom}-${row.urlFrom}-${i}`}
                  className="hover"
                >
                  <td className="font-medium break-all max-w-xs">
                    {row.domainFrom ?? "-"}
                  </td>
                  <td>
                    <span
                      className={`badge badge-sm ${
                        (row.spamScore ?? 0) >= 80
                          ? "badge-error"
                          : (row.spamScore ?? 0) >= 60
                            ? "badge-warning"
                            : "badge-ghost"
                      }`}
                    >
                      {formatDecimal(row.spamScore)}
                    </span>
                  </td>
                  <td>{formatNumber(row.rank)}</td>
                  <td className="text-xs text-base-content/60 break-all max-w-sm truncate">
                    {row.urlFrom ?? "-"}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      ) : null}
    </div>
  );
}
