/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as ProjectRouteRouteImport } from './routes/_project/route'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as Char91DotwellKnownChar93OpenaiAppsChallengeRouteImport } from './routes/[.well-known]/openai-apps-challenge'
import { Route as AppAiRouteImport } from './routes/_app/ai'
import { Route as AppBillingRouteImport } from './routes/_app/billing'
import { Route as AppProjectsRouteImport } from './routes/_app/projects'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppSupportRouteImport } from './routes/_app/support'
import { Route as AuthSignInRouteImport } from './routes/_auth.sign-in'
import { Route as AuthSignUpRouteImport } from './routes/_auth.sign-up'
import { Route as AuthenticatedAcceptInvitationRouteImport } from './routes/_authenticated.accept-invitation'
import { Route as AuthenticatedOauthConsentRouteImport } from './routes/_authenticated.oauth-consent'
import { Route as AuthenticatedSubscribeRouteImport } from './routes/_authenticated.subscribe'
import { Route as ApiAiVisibilityRouteImport } from './routes/api/ai-visibility'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as AppAdminIndexRouteImport } from './routes/_app/admin/index'
import { Route as AppHelpDataforseoApiKeyRouteImport } from './routes/_app/help/dataforseo-api-key'
import { Route as AppHelpOpenrouterApiKeyRouteImport } from './routes/_app/help/openrouter-api-key'
import { Route as AuthenticatedOnboardingIndexRouteImport } from './routes/_authenticated.onboarding.index'
import { Route as AuthenticatedOnboardingChatRouteImport } from './routes/_authenticated.onboarding.chat'
import { Route as ProjectPProjectIdRouteRouteImport } from './routes/_project/p/$projectId/route'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ProjectPProjectIdIndexRouteImport } from './routes/_project/p/$projectId/index'
import { Route as ProjectPProjectIdAuditRouteImport } from './routes/_project/p/$projectId/audit'
import { Route as ProjectPProjectIdBacklinksRouteImport } from './routes/_project/p/$projectId/backlinks'
import { Route as ProjectPProjectIdBrandLookupRouteImport } from './routes/_project/p/$projectId/brand-lookup'
import { Route as ProjectPProjectIdContentGapRouteImport } from './routes/_project/p/$projectId/content-gap'
import { Route as ProjectPProjectIdCrawlBudgetRouteImport } from './routes/_project/p/$projectId/crawl-budget'
import { Route as ProjectPProjectIdDomainRouteImport } from './routes/_project/p/$projectId/domain'
import { Route as ProjectPProjectIdGa4InsightsRouteImport } from './routes/_project/p/$projectId/ga4-insights'
import { Route as ProjectPProjectIdKeywordClusteringRouteImport } from './routes/_project/p/$projectId/keyword-clustering'
import { Route as ProjectPProjectIdKeywordsRouteImport } from './routes/_project/p/$projectId/keywords'
import { Route as ProjectPProjectIdLinkIntersectRouteImport } from './routes/_project/p/$projectId/link-intersect'
import { Route as ProjectPProjectIdOnPageCheckerRouteImport } from './routes/_project/p/$projectId/on-page-checker'
import { Route as ProjectPProjectIdPromptExplorerRouteImport } from './routes/_project/p/$projectId/prompt-explorer'
import { Route as ProjectPProjectIdRankTrackingRouteImport } from './routes/_project/p/$projectId/rank-tracking'
import { Route as ProjectPProjectIdReportsRouteRouteImport } from './routes/_project/p/$projectId/reports/route'
import { Route as ProjectPProjectIdSamRouteImport } from './routes/_project/p/$projectId/sam'
import { Route as ProjectPProjectIdSavedRouteImport } from './routes/_project/p/$projectId/saved'
import { Route as ProjectPProjectIdSearchPerformanceRouteImport } from './routes/_project/p/$projectId/search-performance'
import { Route as ProjectPProjectIdSerpVolatilityRouteImport } from './routes/_project/p/$projectId/serp-volatility'
import { Route as ProjectPProjectIdSettingsRouteImport } from './routes/_project/p/$projectId/settings'
import { Route as ProjectPProjectIdSitemapValidatorRouteImport } from './routes/_project/p/$projectId/sitemap-validator'
import { Route as ApiGa4OauthCallbackRouteImport } from './routes/api/ga4/oauth/callback'
import { Route as ApiGscOauthCallbackRouteImport } from './routes/api/gsc/oauth/callback'
import { Route as ProjectPProjectIdAlertsIndexRouteImport } from './routes/_project/p/$projectId/alerts/index'
import { Route as ProjectPProjectIdAuditIndexRouteImport } from './routes/_project/p/$projectId/audit/index'
import { Route as ProjectPProjectIdRankTrackingIndexRouteImport } from './routes/_project/p/$projectId/rank-tracking/index'
import { Route as ProjectPProjectIdRankTrackingConfigIdRouteImport } from './routes/_project/p/$projectId/rank-tracking/$configId'
import { Route as ProjectPProjectIdReportsIndexRouteImport } from './routes/_project/p/$projectId/reports/index'
import { Route as ProjectPProjectIdReportsReportIdRouteImport } from './routes/_project/p/$projectId/reports/$reportId'
import { Route as ProjectPProjectIdStrategyIndexRouteImport } from './routes/_project/p/$projectId/strategy/index'
import { Route as ProjectPProjectIdAuditIssuesResultIdRouteImport } from './routes/_project/p/$projectId/audit/issues/$resultId'
import { Route as ProjectPProjectIdStrategyBriefsBriefIdRouteImport } from './routes/_project/p/$projectId/strategy/briefs/$briefId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectRouteRoute = ProjectRouteRouteImport.update({
  id: '/_project',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OpenaiAppsChallengeRoute =
  Char91DotwellKnownChar93OpenaiAppsChallengeRouteImport.update({
    id: '/.well-known/openai-apps-challenge',
    path: '/.well-known/openai-apps-challenge',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppAiRoute = AppAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSupportRoute = AppSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AppRouteRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedAcceptInvitationRoute =
  AuthenticatedAcceptInvitationRouteImport.update({
    id: '/accept-invitation',
    path: '/accept-invitation',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOauthConsentRoute =
  AuthenticatedOauthConsentRouteImport.update({
    id: '/oauth-consent',
    path: '/oauth-consent',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSubscribeRoute = AuthenticatedSubscribeRouteImport.update({
  id: '/subscribe',
  path: '/subscribe',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiAiVisibilityRoute = ApiAiVisibilityRouteImport.update({
  id: '/api/ai-visibility',
  path: '/api/ai-visibility',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppHelpDataforseoApiKeyRoute = AppHelpDataforseoApiKeyRouteImport.update({
  id: '/help/dataforseo-api-key',
  path: '/help/dataforseo-api-key',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppHelpOpenrouterApiKeyRoute = AppHelpOpenrouterApiKeyRouteImport.update({
  id: '/help/openrouter-api-key',
  path: '/help/openrouter-api-key',
  getParentRoute: () => AppRouteRoute,
} as any)
const AuthenticatedOnboardingIndexRoute =
  AuthenticatedOnboardingIndexRouteImport.update({
    id: '/onboarding/',
    path: '/onboarding/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOnboardingChatRoute =
  AuthenticatedOnboardingChatRouteImport.update({
    id: '/onboarding/chat',
    path: '/onboarding/chat',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ProjectPProjectIdRouteRoute = ProjectPProjectIdRouteRouteImport.update({
  id: '/p/$projectId',
  path: '/p/$projectId',
  getParentRoute: () => ProjectRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectPProjectIdIndexRoute = ProjectPProjectIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectPProjectIdRouteRoute,
} as any)
const ProjectPProjectIdAuditRoute = ProjectPProjectIdAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => ProjectPProjectIdRouteRoute,
} as any)
const ProjectPProjectIdBacklinksRoute =
  ProjectPProjectIdBacklinksRouteImport.update({
    id: '/backlinks',
    path: '/backlinks',
    getParentRoute: () => ProjectPProjectIdRouteRoute,
  } as any)
const ProjectPProjectIdBrandLookupRoute =
  ProjectPProjectIdBrandLookupRouteImport.update({
    id: '/brand-lookup',
    path: '/brand-lookup',
    getParentRoute: () => ProjectPProjectIdRouteRoute,
  } as any)
const ProjectPProjectIdContentGapRoute =
  ProjectPProjectIdContentGapRouteImport.update({
    id: '/content-gap',
    path: '/content-gap',
    getParentRoute: () => ProjectPProjectIdRouteRoute,
  } as any)
const ProjectPProjectIdCrawlBudgetRoute =
  ProjectPProjectIdCrawlBudgetRouteImport.update({
    id: '/crawl-budget',
    path: '/crawl-budget',
    getParentRoute: () => ProjectPProjectIdRouteRoute,
  } as any)
const ProjectPProjectIdDomainRoute = ProjectPProjectIdDomainRouteImport.update({
  id: '/domain',
  path: '/domain',
  getParentRoute: () => ProjectPProjectIdRouteRoute,
} as any)
const ProjectPProjectIdGa4InsightsRoute =
  ProjectPProjectIdGa4InsightsRouteImport.update({
    id: '/ga4-insights',
    path: '/ga4-insights',
    getParentRoute: () => ProjectPProjectIdRouteRoute,
  } as any)
const ProjectPProjectIdKeywordClusteringRoute =
  ProjectPProjectIdKeywordClusteringRouteImport.update({
    id: '/keyword-clustering',
    path: '/keyword-clustering',
    getParentRoute: () => ProjectPProjectIdRouteRoute,
  } as any)
const ProjectPProjectIdKeywordsRoute =
  ProjectPProjectIdKeywordsRouteImport.update({
    id: '/keywords',
    path: '/keywords',
    getParentRoute: () => ProjectPProjectIdRouteRoute,
  } as any)
const ProjectPProjectIdLinkIntersectRoute =
  ProjectPProjectIdLinkIntersectRouteImport.update({
    id: '/link-intersect',
    path: '/link-intersect',
    getParentRoute: () => ProjectPProjectIdRouteRoute,
  } as any)
const ProjectPProjectIdOnPageCheckerRoute =
  ProjectPProjectIdOnPageCheckerRouteImport.update({
    id: '/on-page-checker',
    path: '/on-page-checker',
    getParentRoute: () => ProjectPProjectIdRouteRoute,
  } as any)
const ProjectPProjectIdPromptExplorerRoute =
  ProjectPProjectIdPromptExplorerRouteImport.update({
    id: '/prompt-explorer',
    path: '/prompt-explorer',
    getParentRoute: () => ProjectPProjectIdRouteRoute,
  } as any)
const ProjectPProjectIdRankTrackingRoute =
  ProjectPProjectIdRankTrackingRouteImport.update({
    id: '/rank-tracking',
    path: '/rank-tracking',
    getParentRoute: () => ProjectPProjectIdRouteRoute,
  } as any)
const ProjectPProjectIdReportsRouteRoute =
  ProjectPProjectIdReportsRouteRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => ProjectPProjectIdRouteRoute,
  } as any)
const ProjectPProjectIdSamRoute = ProjectPProjectIdSamRouteImport.update({
  id: '/sam',
  path: '/sam',
  getParentRoute: () => ProjectPProjectIdRouteRoute,
} as any)
const ProjectPProjectIdSavedRoute = ProjectPProjectIdSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => ProjectPProjectIdRouteRoute,
} as any)
const ProjectPProjectIdSearchPerformanceRoute =
  ProjectPProjectIdSearchPerformanceRouteImport.update({
    id: '/search-performance',
    path: '/search-performance',
    getParentRoute: () => ProjectPProjectIdRouteRoute,
  } as any)
const ProjectPProjectIdSerpVolatilityRoute =
  ProjectPProjectIdSerpVolatilityRouteImport.update({
    id: '/serp-volatility',
    path: '/serp-volatility',
    getParentRoute: () => ProjectPProjectIdRouteRoute,
  } as any)
const ProjectPProjectIdSettingsRoute =
  ProjectPProjectIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => ProjectPProjectIdRouteRoute,
  } as any)
const ProjectPProjectIdSitemapValidatorRoute =
  ProjectPProjectIdSitemapValidatorRouteImport.update({
    id: '/sitemap-validator',
    path: '/sitemap-validator',
    getParentRoute: () => ProjectPProjectIdRouteRoute,
  } as any)
const ApiGa4OauthCallbackRoute = ApiGa4OauthCallbackRouteImport.update({
  id: '/api/ga4/oauth/callback',
  path: '/api/ga4/oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGscOauthCallbackRoute = ApiGscOauthCallbackRouteImport.update({
  id: '/api/gsc/oauth/callback',
  path: '/api/gsc/oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectPProjectIdAlertsIndexRoute =
  ProjectPProjectIdAlertsIndexRouteImport.update({
    id: '/alerts/',
    path: '/alerts/',
    getParentRoute: () => ProjectPProjectIdRouteRoute,
  } as any)
const ProjectPProjectIdAuditIndexRoute =
  ProjectPProjectIdAuditIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProjectPProjectIdAuditRoute,
  } as any)
const ProjectPProjectIdRankTrackingIndexRoute =
  ProjectPProjectIdRankTrackingIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProjectPProjectIdRankTrackingRoute,
  } as any)
const ProjectPProjectIdRankTrackingConfigIdRoute =
  ProjectPProjectIdRankTrackingConfigIdRouteImport.update({
    id: '/$configId',
    path: '/$configId',
    getParentRoute: () => ProjectPProjectIdRankTrackingRoute,
  } as any)
const ProjectPProjectIdReportsIndexRoute =
  ProjectPProjectIdReportsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProjectPProjectIdReportsRouteRoute,
  } as any)
const ProjectPProjectIdReportsReportIdRoute =
  ProjectPProjectIdReportsReportIdRouteImport.update({
    id: '/$reportId',
    path: '/$reportId',
    getParentRoute: () => ProjectPProjectIdReportsRouteRoute,
  } as any)
const ProjectPProjectIdStrategyIndexRoute =
  ProjectPProjectIdStrategyIndexRouteImport.update({
    id: '/strategy/',
    path: '/strategy/',
    getParentRoute: () => ProjectPProjectIdRouteRoute,
  } as any)
const ProjectPProjectIdAuditIssuesResultIdRoute =
  ProjectPProjectIdAuditIssuesResultIdRouteImport.update({
    id: '/issues/$resultId',
    path: '/issues/$resultId',
    getParentRoute: () => ProjectPProjectIdAuditRoute,
  } as any)
const ProjectPProjectIdStrategyBriefsBriefIdRoute =
  ProjectPProjectIdStrategyBriefsBriefIdRouteImport.update({
    id: '/strategy/briefs/$briefId',
    path: '/strategy/briefs/$briefId',
    getParentRoute: () => ProjectPProjectIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/.well-known/openai-apps-challenge': typeof Char91DotwellKnownChar93OpenaiAppsChallengeRoute
  '/ai': typeof AppAiRoute
  '/billing': typeof AppBillingRoute
  '/projects': typeof AppProjectsRoute
  '/settings': typeof AppSettingsRoute
  '/support': typeof AppSupportRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/accept-invitation': typeof AuthenticatedAcceptInvitationRoute
  '/oauth-consent': typeof AuthenticatedOauthConsentRoute
  '/subscribe': typeof AuthenticatedSubscribeRoute
  '/api/ai-visibility': typeof ApiAiVisibilityRoute
  '/api/health': typeof ApiHealthRoute
  '/p/$projectId': typeof ProjectPProjectIdRouteRouteWithChildren
  '/help/dataforseo-api-key': typeof AppHelpDataforseoApiKeyRoute
  '/help/openrouter-api-key': typeof AppHelpOpenrouterApiKeyRoute
  '/onboarding/chat': typeof AuthenticatedOnboardingChatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/': typeof AppAdminIndexRoute
  '/onboarding/': typeof AuthenticatedOnboardingIndexRoute
  '/p/$projectId/reports': typeof ProjectPProjectIdReportsRouteRouteWithChildren
  '/p/$projectId/audit': typeof ProjectPProjectIdAuditRouteWithChildren
  '/p/$projectId/backlinks': typeof ProjectPProjectIdBacklinksRoute
  '/p/$projectId/brand-lookup': typeof ProjectPProjectIdBrandLookupRoute
  '/p/$projectId/content-gap': typeof ProjectPProjectIdContentGapRoute
  '/p/$projectId/crawl-budget': typeof ProjectPProjectIdCrawlBudgetRoute
  '/p/$projectId/domain': typeof ProjectPProjectIdDomainRoute
  '/p/$projectId/ga4-insights': typeof ProjectPProjectIdGa4InsightsRoute
  '/p/$projectId/keyword-clustering': typeof ProjectPProjectIdKeywordClusteringRoute
  '/p/$projectId/keywords': typeof ProjectPProjectIdKeywordsRoute
  '/p/$projectId/link-intersect': typeof ProjectPProjectIdLinkIntersectRoute
  '/p/$projectId/on-page-checker': typeof ProjectPProjectIdOnPageCheckerRoute
  '/p/$projectId/prompt-explorer': typeof ProjectPProjectIdPromptExplorerRoute
  '/p/$projectId/rank-tracking': typeof ProjectPProjectIdRankTrackingRouteWithChildren
  '/p/$projectId/sam': typeof ProjectPProjectIdSamRoute
  '/p/$projectId/saved': typeof ProjectPProjectIdSavedRoute
  '/p/$projectId/search-performance': typeof ProjectPProjectIdSearchPerformanceRoute
  '/p/$projectId/serp-volatility': typeof ProjectPProjectIdSerpVolatilityRoute
  '/p/$projectId/settings': typeof ProjectPProjectIdSettingsRoute
  '/p/$projectId/sitemap-validator': typeof ProjectPProjectIdSitemapValidatorRoute
  '/api/ga4/oauth/callback': typeof ApiGa4OauthCallbackRoute
  '/api/gsc/oauth/callback': typeof ApiGscOauthCallbackRoute
  '/p/$projectId/': typeof ProjectPProjectIdIndexRoute
  '/p/$projectId/rank-tracking/$configId': typeof ProjectPProjectIdRankTrackingConfigIdRoute
  '/p/$projectId/reports/$reportId': typeof ProjectPProjectIdReportsReportIdRoute
  '/p/$projectId/alerts/': typeof ProjectPProjectIdAlertsIndexRoute
  '/p/$projectId/audit/': typeof ProjectPProjectIdAuditIndexRoute
  '/p/$projectId/rank-tracking/': typeof ProjectPProjectIdRankTrackingIndexRoute
  '/p/$projectId/reports/': typeof ProjectPProjectIdReportsIndexRoute
  '/p/$projectId/strategy/': typeof ProjectPProjectIdStrategyIndexRoute
  '/p/$projectId/audit/issues/$resultId': typeof ProjectPProjectIdAuditIssuesResultIdRoute
  '/p/$projectId/strategy/briefs/$briefId': typeof ProjectPProjectIdStrategyBriefsBriefIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/.well-known/openai-apps-challenge': typeof Char91DotwellKnownChar93OpenaiAppsChallengeRoute
  '/ai': typeof AppAiRoute
  '/billing': typeof AppBillingRoute
  '/projects': typeof AppProjectsRoute
  '/settings': typeof AppSettingsRoute
  '/support': typeof AppSupportRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/accept-invitation': typeof AuthenticatedAcceptInvitationRoute
  '/oauth-consent': typeof AuthenticatedOauthConsentRoute
  '/subscribe': typeof AuthenticatedSubscribeRoute
  '/api/ai-visibility': typeof ApiAiVisibilityRoute
  '/api/health': typeof ApiHealthRoute
  '/help/dataforseo-api-key': typeof AppHelpDataforseoApiKeyRoute
  '/help/openrouter-api-key': typeof AppHelpOpenrouterApiKeyRoute
  '/onboarding/chat': typeof AuthenticatedOnboardingChatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin': typeof AppAdminIndexRoute
  '/onboarding': typeof AuthenticatedOnboardingIndexRoute
  '/p/$projectId/backlinks': typeof ProjectPProjectIdBacklinksRoute
  '/p/$projectId/brand-lookup': typeof ProjectPProjectIdBrandLookupRoute
  '/p/$projectId/content-gap': typeof ProjectPProjectIdContentGapRoute
  '/p/$projectId/crawl-budget': typeof ProjectPProjectIdCrawlBudgetRoute
  '/p/$projectId/domain': typeof ProjectPProjectIdDomainRoute
  '/p/$projectId/ga4-insights': typeof ProjectPProjectIdGa4InsightsRoute
  '/p/$projectId/keyword-clustering': typeof ProjectPProjectIdKeywordClusteringRoute
  '/p/$projectId/keywords': typeof ProjectPProjectIdKeywordsRoute
  '/p/$projectId/link-intersect': typeof ProjectPProjectIdLinkIntersectRoute
  '/p/$projectId/on-page-checker': typeof ProjectPProjectIdOnPageCheckerRoute
  '/p/$projectId/prompt-explorer': typeof ProjectPProjectIdPromptExplorerRoute
  '/p/$projectId/sam': typeof ProjectPProjectIdSamRoute
  '/p/$projectId/saved': typeof ProjectPProjectIdSavedRoute
  '/p/$projectId/search-performance': typeof ProjectPProjectIdSearchPerformanceRoute
  '/p/$projectId/serp-volatility': typeof ProjectPProjectIdSerpVolatilityRoute
  '/p/$projectId/settings': typeof ProjectPProjectIdSettingsRoute
  '/p/$projectId/sitemap-validator': typeof ProjectPProjectIdSitemapValidatorRoute
  '/api/ga4/oauth/callback': typeof ApiGa4OauthCallbackRoute
  '/api/gsc/oauth/callback': typeof ApiGscOauthCallbackRoute
  '/p/$projectId': typeof ProjectPProjectIdIndexRoute
  '/p/$projectId/rank-tracking/$configId': typeof ProjectPProjectIdRankTrackingConfigIdRoute
  '/p/$projectId/reports/$reportId': typeof ProjectPProjectIdReportsReportIdRoute
  '/p/$projectId/alerts': typeof ProjectPProjectIdAlertsIndexRoute
  '/p/$projectId/audit': typeof ProjectPProjectIdAuditIndexRoute
  '/p/$projectId/rank-tracking': typeof ProjectPProjectIdRankTrackingIndexRoute
  '/p/$projectId/reports': typeof ProjectPProjectIdReportsIndexRoute
  '/p/$projectId/strategy': typeof ProjectPProjectIdStrategyIndexRoute
  '/p/$projectId/audit/issues/$resultId': typeof ProjectPProjectIdAuditIssuesResultIdRoute
  '/p/$projectId/strategy/briefs/$briefId': typeof ProjectPProjectIdStrategyBriefsBriefIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/_project': typeof ProjectRouteRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/.well-known/openai-apps-challenge': typeof Char91DotwellKnownChar93OpenaiAppsChallengeRoute
  '/_app/ai': typeof AppAiRoute
  '/_app/billing': typeof AppBillingRoute
  '/_app/projects': typeof AppProjectsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/support': typeof AppSupportRoute
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/_authenticated/accept-invitation': typeof AuthenticatedAcceptInvitationRoute
  '/_authenticated/oauth-consent': typeof AuthenticatedOauthConsentRoute
  '/_authenticated/subscribe': typeof AuthenticatedSubscribeRoute
  '/api/ai-visibility': typeof ApiAiVisibilityRoute
  '/api/health': typeof ApiHealthRoute
  '/_project/p/$projectId': typeof ProjectPProjectIdRouteRouteWithChildren
  '/_app/help/dataforseo-api-key': typeof AppHelpDataforseoApiKeyRoute
  '/_app/help/openrouter-api-key': typeof AppHelpOpenrouterApiKeyRoute
  '/_authenticated/onboarding/chat': typeof AuthenticatedOnboardingChatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_app/admin/': typeof AppAdminIndexRoute
  '/_authenticated/onboarding/': typeof AuthenticatedOnboardingIndexRoute
  '/_project/p/$projectId/reports': typeof ProjectPProjectIdReportsRouteRouteWithChildren
  '/_project/p/$projectId/audit': typeof ProjectPProjectIdAuditRouteWithChildren
  '/_project/p/$projectId/backlinks': typeof ProjectPProjectIdBacklinksRoute
  '/_project/p/$projectId/brand-lookup': typeof ProjectPProjectIdBrandLookupRoute
  '/_project/p/$projectId/content-gap': typeof ProjectPProjectIdContentGapRoute
  '/_project/p/$projectId/crawl-budget': typeof ProjectPProjectIdCrawlBudgetRoute
  '/_project/p/$projectId/domain': typeof ProjectPProjectIdDomainRoute
  '/_project/p/$projectId/ga4-insights': typeof ProjectPProjectIdGa4InsightsRoute
  '/_project/p/$projectId/keyword-clustering': typeof ProjectPProjectIdKeywordClusteringRoute
  '/_project/p/$projectId/keywords': typeof ProjectPProjectIdKeywordsRoute
  '/_project/p/$projectId/link-intersect': typeof ProjectPProjectIdLinkIntersectRoute
  '/_project/p/$projectId/on-page-checker': typeof ProjectPProjectIdOnPageCheckerRoute
  '/_project/p/$projectId/prompt-explorer': typeof ProjectPProjectIdPromptExplorerRoute
  '/_project/p/$projectId/rank-tracking': typeof ProjectPProjectIdRankTrackingRouteWithChildren
  '/_project/p/$projectId/sam': typeof ProjectPProjectIdSamRoute
  '/_project/p/$projectId/saved': typeof ProjectPProjectIdSavedRoute
  '/_project/p/$projectId/search-performance': typeof ProjectPProjectIdSearchPerformanceRoute
  '/_project/p/$projectId/serp-volatility': typeof ProjectPProjectIdSerpVolatilityRoute
  '/_project/p/$projectId/settings': typeof ProjectPProjectIdSettingsRoute
  '/_project/p/$projectId/sitemap-validator': typeof ProjectPProjectIdSitemapValidatorRoute
  '/api/ga4/oauth/callback': typeof ApiGa4OauthCallbackRoute
  '/api/gsc/oauth/callback': typeof ApiGscOauthCallbackRoute
  '/_project/p/$projectId/': typeof ProjectPProjectIdIndexRoute
  '/_project/p/$projectId/rank-tracking/$configId': typeof ProjectPProjectIdRankTrackingConfigIdRoute
  '/_project/p/$projectId/reports/$reportId': typeof ProjectPProjectIdReportsReportIdRoute
  '/_project/p/$projectId/alerts/': typeof ProjectPProjectIdAlertsIndexRoute
  '/_project/p/$projectId/audit/': typeof ProjectPProjectIdAuditIndexRoute
  '/_project/p/$projectId/rank-tracking/': typeof ProjectPProjectIdRankTrackingIndexRoute
  '/_project/p/$projectId/reports/': typeof ProjectPProjectIdReportsIndexRoute
  '/_project/p/$projectId/strategy/': typeof ProjectPProjectIdStrategyIndexRoute
  '/_project/p/$projectId/audit/issues/$resultId': typeof ProjectPProjectIdAuditIssuesResultIdRoute
  '/_project/p/$projectId/strategy/briefs/$briefId': typeof ProjectPProjectIdStrategyBriefsBriefIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/pricing'
    | '/reset-password'
    | '/verify-email'
    | '/.well-known/openai-apps-challenge'
    | '/ai'
    | '/billing'
    | '/projects'
    | '/settings'
    | '/support'
    | '/sign-in'
    | '/sign-up'
    | '/accept-invitation'
    | '/oauth-consent'
    | '/subscribe'
    | '/api/ai-visibility'
    | '/api/health'
    | '/p/$projectId'
    | '/help/dataforseo-api-key'
    | '/help/openrouter-api-key'
    | '/onboarding/chat'
    | '/api/auth/$'
    | '/admin/'
    | '/onboarding/'
    | '/p/$projectId/reports'
    | '/p/$projectId/audit'
    | '/p/$projectId/backlinks'
    | '/p/$projectId/brand-lookup'
    | '/p/$projectId/content-gap'
    | '/p/$projectId/crawl-budget'
    | '/p/$projectId/domain'
    | '/p/$projectId/ga4-insights'
    | '/p/$projectId/keyword-clustering'
    | '/p/$projectId/keywords'
    | '/p/$projectId/link-intersect'
    | '/p/$projectId/on-page-checker'
    | '/p/$projectId/prompt-explorer'
    | '/p/$projectId/rank-tracking'
    | '/p/$projectId/sam'
    | '/p/$projectId/saved'
    | '/p/$projectId/search-performance'
    | '/p/$projectId/serp-volatility'
    | '/p/$projectId/settings'
    | '/p/$projectId/sitemap-validator'
    | '/api/ga4/oauth/callback'
    | '/api/gsc/oauth/callback'
    | '/p/$projectId/'
    | '/p/$projectId/rank-tracking/$configId'
    | '/p/$projectId/reports/$reportId'
    | '/p/$projectId/alerts/'
    | '/p/$projectId/audit/'
    | '/p/$projectId/rank-tracking/'
    | '/p/$projectId/reports/'
    | '/p/$projectId/strategy/'
    | '/p/$projectId/audit/issues/$resultId'
    | '/p/$projectId/strategy/briefs/$briefId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/pricing'
    | '/reset-password'
    | '/verify-email'
    | '/.well-known/openai-apps-challenge'
    | '/ai'
    | '/billing'
    | '/projects'
    | '/settings'
    | '/support'
    | '/sign-in'
    | '/sign-up'
    | '/accept-invitation'
    | '/oauth-consent'
    | '/subscribe'
    | '/api/ai-visibility'
    | '/api/health'
    | '/help/dataforseo-api-key'
    | '/help/openrouter-api-key'
    | '/onboarding/chat'
    | '/api/auth/$'
    | '/admin'
    | '/onboarding'
    | '/p/$projectId/backlinks'
    | '/p/$projectId/brand-lookup'
    | '/p/$projectId/content-gap'
    | '/p/$projectId/crawl-budget'
    | '/p/$projectId/domain'
    | '/p/$projectId/ga4-insights'
    | '/p/$projectId/keyword-clustering'
    | '/p/$projectId/keywords'
    | '/p/$projectId/link-intersect'
    | '/p/$projectId/on-page-checker'
    | '/p/$projectId/prompt-explorer'
    | '/p/$projectId/sam'
    | '/p/$projectId/saved'
    | '/p/$projectId/search-performance'
    | '/p/$projectId/serp-volatility'
    | '/p/$projectId/settings'
    | '/p/$projectId/sitemap-validator'
    | '/api/ga4/oauth/callback'
    | '/api/gsc/oauth/callback'
    | '/p/$projectId'
    | '/p/$projectId/rank-tracking/$configId'
    | '/p/$projectId/reports/$reportId'
    | '/p/$projectId/alerts'
    | '/p/$projectId/audit'
    | '/p/$projectId/rank-tracking'
    | '/p/$projectId/reports'
    | '/p/$projectId/strategy'
    | '/p/$projectId/audit/issues/$resultId'
    | '/p/$projectId/strategy/briefs/$briefId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_project'
    | '/_auth'
    | '/_authenticated'
    | '/forgot-password'
    | '/pricing'
    | '/reset-password'
    | '/verify-email'
    | '/.well-known/openai-apps-challenge'
    | '/_app/ai'
    | '/_app/billing'
    | '/_app/projects'
    | '/_app/settings'
    | '/_app/support'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/_authenticated/accept-invitation'
    | '/_authenticated/oauth-consent'
    | '/_authenticated/subscribe'
    | '/api/ai-visibility'
    | '/api/health'
    | '/_project/p/$projectId'
    | '/_app/help/dataforseo-api-key'
    | '/_app/help/openrouter-api-key'
    | '/_authenticated/onboarding/chat'
    | '/api/auth/$'
    | '/_app/admin/'
    | '/_authenticated/onboarding/'
    | '/_project/p/$projectId/reports'
    | '/_project/p/$projectId/audit'
    | '/_project/p/$projectId/backlinks'
    | '/_project/p/$projectId/brand-lookup'
    | '/_project/p/$projectId/content-gap'
    | '/_project/p/$projectId/crawl-budget'
    | '/_project/p/$projectId/domain'
    | '/_project/p/$projectId/ga4-insights'
    | '/_project/p/$projectId/keyword-clustering'
    | '/_project/p/$projectId/keywords'
    | '/_project/p/$projectId/link-intersect'
    | '/_project/p/$projectId/on-page-checker'
    | '/_project/p/$projectId/prompt-explorer'
    | '/_project/p/$projectId/rank-tracking'
    | '/_project/p/$projectId/sam'
    | '/_project/p/$projectId/saved'
    | '/_project/p/$projectId/search-performance'
    | '/_project/p/$projectId/serp-volatility'
    | '/_project/p/$projectId/settings'
    | '/_project/p/$projectId/sitemap-validator'
    | '/api/ga4/oauth/callback'
    | '/api/gsc/oauth/callback'
    | '/_project/p/$projectId/'
    | '/_project/p/$projectId/rank-tracking/$configId'
    | '/_project/p/$projectId/reports/$reportId'
    | '/_project/p/$projectId/alerts/'
    | '/_project/p/$projectId/audit/'
    | '/_project/p/$projectId/rank-tracking/'
    | '/_project/p/$projectId/reports/'
    | '/_project/p/$projectId/strategy/'
    | '/_project/p/$projectId/audit/issues/$resultId'
    | '/_project/p/$projectId/strategy/briefs/$briefId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  ProjectRouteRoute: typeof ProjectRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  PricingRoute: typeof PricingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  Char91DotwellKnownChar93OpenaiAppsChallengeRoute: typeof Char91DotwellKnownChar93OpenaiAppsChallengeRoute
  ApiAiVisibilityRoute: typeof ApiAiVisibilityRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiGa4OauthCallbackRoute: typeof ApiGa4OauthCallbackRoute
  ApiGscOauthCallbackRoute: typeof ApiGscOauthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_project': {
      id: '/_project'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProjectRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/openai-apps-challenge': {
      id: '/.well-known/openai-apps-challenge'
      path: '/.well-known/openai-apps-challenge'
      fullPath: '/.well-known/openai-apps-challenge'
      preLoaderRoute: typeof Char91DotwellKnownChar93OpenaiAppsChallengeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/ai': {
      id: '/_app/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AppAiRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/billing': {
      id: '/_app/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/projects': {
      id: '/_app/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/support': {
      id: '/_app/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AppSupportRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/accept-invitation': {
      id: '/_authenticated/accept-invitation'
      path: '/accept-invitation'
      fullPath: '/accept-invitation'
      preLoaderRoute: typeof AuthenticatedAcceptInvitationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/oauth-consent': {
      id: '/_authenticated/oauth-consent'
      path: '/oauth-consent'
      fullPath: '/oauth-consent'
      preLoaderRoute: typeof AuthenticatedOauthConsentRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/subscribe': {
      id: '/_authenticated/subscribe'
      path: '/subscribe'
      fullPath: '/subscribe'
      preLoaderRoute: typeof AuthenticatedSubscribeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/ai-visibility': {
      id: '/api/ai-visibility'
      path: '/api/ai-visibility'
      fullPath: '/api/ai-visibility'
      preLoaderRoute: typeof ApiAiVisibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/admin/': {
      id: '/_app/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/help/dataforseo-api-key': {
      id: '/_app/help/dataforseo-api-key'
      path: '/help/dataforseo-api-key'
      fullPath: '/help/dataforseo-api-key'
      preLoaderRoute: typeof AppHelpDataforseoApiKeyRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/help/openrouter-api-key': {
      id: '/_app/help/openrouter-api-key'
      path: '/help/openrouter-api-key'
      fullPath: '/help/openrouter-api-key'
      preLoaderRoute: typeof AppHelpOpenrouterApiKeyRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_authenticated/onboarding/': {
      id: '/_authenticated/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof AuthenticatedOnboardingIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding/chat': {
      id: '/_authenticated/onboarding/chat'
      path: '/onboarding/chat'
      fullPath: '/onboarding/chat'
      preLoaderRoute: typeof AuthenticatedOnboardingChatRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_project/p/$projectId': {
      id: '/_project/p/$projectId'
      path: '/p/$projectId'
      fullPath: '/p/$projectId'
      preLoaderRoute: typeof ProjectPProjectIdRouteRouteImport
      parentRoute: typeof ProjectRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_project/p/$projectId/': {
      id: '/_project/p/$projectId/'
      path: '/'
      fullPath: '/p/$projectId/'
      preLoaderRoute: typeof ProjectPProjectIdIndexRouteImport
      parentRoute: typeof ProjectPProjectIdRouteRoute
    }
    '/_project/p/$projectId/audit': {
      id: '/_project/p/$projectId/audit'
      path: '/audit'
      fullPath: '/p/$projectId/audit'
      preLoaderRoute: typeof ProjectPProjectIdAuditRouteImport
      parentRoute: typeof ProjectPProjectIdRouteRoute
    }
    '/_project/p/$projectId/backlinks': {
      id: '/_project/p/$projectId/backlinks'
      path: '/backlinks'
      fullPath: '/p/$projectId/backlinks'
      preLoaderRoute: typeof ProjectPProjectIdBacklinksRouteImport
      parentRoute: typeof ProjectPProjectIdRouteRoute
    }
    '/_project/p/$projectId/brand-lookup': {
      id: '/_project/p/$projectId/brand-lookup'
      path: '/brand-lookup'
      fullPath: '/p/$projectId/brand-lookup'
      preLoaderRoute: typeof ProjectPProjectIdBrandLookupRouteImport
      parentRoute: typeof ProjectPProjectIdRouteRoute
    }
    '/_project/p/$projectId/content-gap': {
      id: '/_project/p/$projectId/content-gap'
      path: '/content-gap'
      fullPath: '/p/$projectId/content-gap'
      preLoaderRoute: typeof ProjectPProjectIdContentGapRouteImport
      parentRoute: typeof ProjectPProjectIdRouteRoute
    }
    '/_project/p/$projectId/crawl-budget': {
      id: '/_project/p/$projectId/crawl-budget'
      path: '/crawl-budget'
      fullPath: '/p/$projectId/crawl-budget'
      preLoaderRoute: typeof ProjectPProjectIdCrawlBudgetRouteImport
      parentRoute: typeof ProjectPProjectIdRouteRoute
    }
    '/_project/p/$projectId/domain': {
      id: '/_project/p/$projectId/domain'
      path: '/domain'
      fullPath: '/p/$projectId/domain'
      preLoaderRoute: typeof ProjectPProjectIdDomainRouteImport
      parentRoute: typeof ProjectPProjectIdRouteRoute
    }
    '/_project/p/$projectId/ga4-insights': {
      id: '/_project/p/$projectId/ga4-insights'
      path: '/ga4-insights'
      fullPath: '/p/$projectId/ga4-insights'
      preLoaderRoute: typeof ProjectPProjectIdGa4InsightsRouteImport
      parentRoute: typeof ProjectPProjectIdRouteRoute
    }
    '/_project/p/$projectId/keyword-clustering': {
      id: '/_project/p/$projectId/keyword-clustering'
      path: '/keyword-clustering'
      fullPath: '/p/$projectId/keyword-clustering'
      preLoaderRoute: typeof ProjectPProjectIdKeywordClusteringRouteImport
      parentRoute: typeof ProjectPProjectIdRouteRoute
    }
    '/_project/p/$projectId/keywords': {
      id: '/_project/p/$projectId/keywords'
      path: '/keywords'
      fullPath: '/p/$projectId/keywords'
      preLoaderRoute: typeof ProjectPProjectIdKeywordsRouteImport
      parentRoute: typeof ProjectPProjectIdRouteRoute
    }
    '/_project/p/$projectId/link-intersect': {
      id: '/_project/p/$projectId/link-intersect'
      path: '/link-intersect'
      fullPath: '/p/$projectId/link-intersect'
      preLoaderRoute: typeof ProjectPProjectIdLinkIntersectRouteImport
      parentRoute: typeof ProjectPProjectIdRouteRoute
    }
    '/_project/p/$projectId/on-page-checker': {
      id: '/_project/p/$projectId/on-page-checker'
      path: '/on-page-checker'
      fullPath: '/p/$projectId/on-page-checker'
      preLoaderRoute: typeof ProjectPProjectIdOnPageCheckerRouteImport
      parentRoute: typeof ProjectPProjectIdRouteRoute
    }
    '/_project/p/$projectId/prompt-explorer': {
      id: '/_project/p/$projectId/prompt-explorer'
      path: '/prompt-explorer'
      fullPath: '/p/$projectId/prompt-explorer'
      preLoaderRoute: typeof ProjectPProjectIdPromptExplorerRouteImport
      parentRoute: typeof ProjectPProjectIdRouteRoute
    }
    '/_project/p/$projectId/rank-tracking': {
      id: '/_project/p/$projectId/rank-tracking'
      path: '/rank-tracking'
      fullPath: '/p/$projectId/rank-tracking'
      preLoaderRoute: typeof ProjectPProjectIdRankTrackingRouteImport
      parentRoute: typeof ProjectPProjectIdRouteRoute
    }
    '/_project/p/$projectId/reports': {
      id: '/_project/p/$projectId/reports'
      path: '/reports'
      fullPath: '/p/$projectId/reports'
      preLoaderRoute: typeof ProjectPProjectIdReportsRouteRouteImport
      parentRoute: typeof ProjectPProjectIdRouteRoute
    }
    '/_project/p/$projectId/sam': {
      id: '/_project/p/$projectId/sam'
      path: '/sam'
      fullPath: '/p/$projectId/sam'
      preLoaderRoute: typeof ProjectPProjectIdSamRouteImport
      parentRoute: typeof ProjectPProjectIdRouteRoute
    }
    '/_project/p/$projectId/saved': {
      id: '/_project/p/$projectId/saved'
      path: '/saved'
      fullPath: '/p/$projectId/saved'
      preLoaderRoute: typeof ProjectPProjectIdSavedRouteImport
      parentRoute: typeof ProjectPProjectIdRouteRoute
    }
    '/_project/p/$projectId/search-performance': {
      id: '/_project/p/$projectId/search-performance'
      path: '/search-performance'
      fullPath: '/p/$projectId/search-performance'
      preLoaderRoute: typeof ProjectPProjectIdSearchPerformanceRouteImport
      parentRoute: typeof ProjectPProjectIdRouteRoute
    }
    '/_project/p/$projectId/serp-volatility': {
      id: '/_project/p/$projectId/serp-volatility'
      path: '/serp-volatility'
      fullPath: '/p/$projectId/serp-volatility'
      preLoaderRoute: typeof ProjectPProjectIdSerpVolatilityRouteImport
      parentRoute: typeof ProjectPProjectIdRouteRoute
    }
    '/_project/p/$projectId/settings': {
      id: '/_project/p/$projectId/settings'
      path: '/settings'
      fullPath: '/p/$projectId/settings'
      preLoaderRoute: typeof ProjectPProjectIdSettingsRouteImport
      parentRoute: typeof ProjectPProjectIdRouteRoute
    }
    '/_project/p/$projectId/sitemap-validator': {
      id: '/_project/p/$projectId/sitemap-validator'
      path: '/sitemap-validator'
      fullPath: '/p/$projectId/sitemap-validator'
      preLoaderRoute: typeof ProjectPProjectIdSitemapValidatorRouteImport
      parentRoute: typeof ProjectPProjectIdRouteRoute
    }
    '/api/ga4/oauth/callback': {
      id: '/api/ga4/oauth/callback'
      path: '/api/ga4/oauth/callback'
      fullPath: '/api/ga4/oauth/callback'
      preLoaderRoute: typeof ApiGa4OauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gsc/oauth/callback': {
      id: '/api/gsc/oauth/callback'
      path: '/api/gsc/oauth/callback'
      fullPath: '/api/gsc/oauth/callback'
      preLoaderRoute: typeof ApiGscOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_project/p/$projectId/alerts/': {
      id: '/_project/p/$projectId/alerts/'
      path: '/alerts'
      fullPath: '/p/$projectId/alerts/'
      preLoaderRoute: typeof ProjectPProjectIdAlertsIndexRouteImport
      parentRoute: typeof ProjectPProjectIdRouteRoute
    }
    '/_project/p/$projectId/audit/': {
      id: '/_project/p/$projectId/audit/'
      path: '/'
      fullPath: '/p/$projectId/audit/'
      preLoaderRoute: typeof ProjectPProjectIdAuditIndexRouteImport
      parentRoute: typeof ProjectPProjectIdAuditRoute
    }
    '/_project/p/$projectId/rank-tracking/': {
      id: '/_project/p/$projectId/rank-tracking/'
      path: '/'
      fullPath: '/p/$projectId/rank-tracking/'
      preLoaderRoute: typeof ProjectPProjectIdRankTrackingIndexRouteImport
      parentRoute: typeof ProjectPProjectIdRankTrackingRoute
    }
    '/_project/p/$projectId/rank-tracking/$configId': {
      id: '/_project/p/$projectId/rank-tracking/$configId'
      path: '/$configId'
      fullPath: '/p/$projectId/rank-tracking/$configId'
      preLoaderRoute: typeof ProjectPProjectIdRankTrackingConfigIdRouteImport
      parentRoute: typeof ProjectPProjectIdRankTrackingRoute
    }
    '/_project/p/$projectId/reports/': {
      id: '/_project/p/$projectId/reports/'
      path: '/'
      fullPath: '/p/$projectId/reports/'
      preLoaderRoute: typeof ProjectPProjectIdReportsIndexRouteImport
      parentRoute: typeof ProjectPProjectIdReportsRouteRoute
    }
    '/_project/p/$projectId/reports/$reportId': {
      id: '/_project/p/$projectId/reports/$reportId'
      path: '/$reportId'
      fullPath: '/p/$projectId/reports/$reportId'
      preLoaderRoute: typeof ProjectPProjectIdReportsReportIdRouteImport
      parentRoute: typeof ProjectPProjectIdReportsRouteRoute
    }
    '/_project/p/$projectId/strategy/': {
      id: '/_project/p/$projectId/strategy/'
      path: '/strategy'
      fullPath: '/p/$projectId/strategy/'
      preLoaderRoute: typeof ProjectPProjectIdStrategyIndexRouteImport
      parentRoute: typeof ProjectPProjectIdRouteRoute
    }
    '/_project/p/$projectId/audit/issues/$resultId': {
      id: '/_project/p/$projectId/audit/issues/$resultId'
      path: '/issues/$resultId'
      fullPath: '/p/$projectId/audit/issues/$resultId'
      preLoaderRoute: typeof ProjectPProjectIdAuditIssuesResultIdRouteImport
      parentRoute: typeof ProjectPProjectIdAuditRoute
    }
    '/_project/p/$projectId/strategy/briefs/$briefId': {
      id: '/_project/p/$projectId/strategy/briefs/$briefId'
      path: '/strategy/briefs/$briefId'
      fullPath: '/p/$projectId/strategy/briefs/$briefId'
      preLoaderRoute: typeof ProjectPProjectIdStrategyBriefsBriefIdRouteImport
      parentRoute: typeof ProjectPProjectIdRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppAiRoute: typeof AppAiRoute
  AppBillingRoute: typeof AppBillingRoute
  AppProjectsRoute: typeof AppProjectsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSupportRoute: typeof AppSupportRoute
  AppHelpDataforseoApiKeyRoute: typeof AppHelpDataforseoApiKeyRoute
  AppHelpOpenrouterApiKeyRoute: typeof AppHelpOpenrouterApiKeyRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAiRoute: AppAiRoute,
  AppBillingRoute: AppBillingRoute,
  AppProjectsRoute: AppProjectsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSupportRoute: AppSupportRoute,
  AppHelpDataforseoApiKeyRoute: AppHelpDataforseoApiKeyRoute,
  AppHelpOpenrouterApiKeyRoute: AppHelpOpenrouterApiKeyRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface ProjectPProjectIdReportsRouteRouteChildren {
  ProjectPProjectIdReportsReportIdRoute: typeof ProjectPProjectIdReportsReportIdRoute
  ProjectPProjectIdReportsIndexRoute: typeof ProjectPProjectIdReportsIndexRoute
}

const ProjectPProjectIdReportsRouteRouteChildren: ProjectPProjectIdReportsRouteRouteChildren =
  {
    ProjectPProjectIdReportsReportIdRoute:
      ProjectPProjectIdReportsReportIdRoute,
    ProjectPProjectIdReportsIndexRoute: ProjectPProjectIdReportsIndexRoute,
  }

const ProjectPProjectIdReportsRouteRouteWithChildren =
  ProjectPProjectIdReportsRouteRoute._addFileChildren(
    ProjectPProjectIdReportsRouteRouteChildren,
  )

interface ProjectPProjectIdAuditRouteChildren {
  ProjectPProjectIdAuditIndexRoute: typeof ProjectPProjectIdAuditIndexRoute
  ProjectPProjectIdAuditIssuesResultIdRoute: typeof ProjectPProjectIdAuditIssuesResultIdRoute
}

const ProjectPProjectIdAuditRouteChildren: ProjectPProjectIdAuditRouteChildren =
  {
    ProjectPProjectIdAuditIndexRoute: ProjectPProjectIdAuditIndexRoute,
    ProjectPProjectIdAuditIssuesResultIdRoute:
      ProjectPProjectIdAuditIssuesResultIdRoute,
  }

const ProjectPProjectIdAuditRouteWithChildren =
  ProjectPProjectIdAuditRoute._addFileChildren(
    ProjectPProjectIdAuditRouteChildren,
  )

interface ProjectPProjectIdRankTrackingRouteChildren {
  ProjectPProjectIdRankTrackingConfigIdRoute: typeof ProjectPProjectIdRankTrackingConfigIdRoute
  ProjectPProjectIdRankTrackingIndexRoute: typeof ProjectPProjectIdRankTrackingIndexRoute
}

const ProjectPProjectIdRankTrackingRouteChildren: ProjectPProjectIdRankTrackingRouteChildren =
  {
    ProjectPProjectIdRankTrackingConfigIdRoute:
      ProjectPProjectIdRankTrackingConfigIdRoute,
    ProjectPProjectIdRankTrackingIndexRoute:
      ProjectPProjectIdRankTrackingIndexRoute,
  }

const ProjectPProjectIdRankTrackingRouteWithChildren =
  ProjectPProjectIdRankTrackingRoute._addFileChildren(
    ProjectPProjectIdRankTrackingRouteChildren,
  )

interface ProjectPProjectIdRouteRouteChildren {
  ProjectPProjectIdReportsRouteRoute: typeof ProjectPProjectIdReportsRouteRouteWithChildren
  ProjectPProjectIdAuditRoute: typeof ProjectPProjectIdAuditRouteWithChildren
  ProjectPProjectIdBacklinksRoute: typeof ProjectPProjectIdBacklinksRoute
  ProjectPProjectIdBrandLookupRoute: typeof ProjectPProjectIdBrandLookupRoute
  ProjectPProjectIdContentGapRoute: typeof ProjectPProjectIdContentGapRoute
  ProjectPProjectIdCrawlBudgetRoute: typeof ProjectPProjectIdCrawlBudgetRoute
  ProjectPProjectIdDomainRoute: typeof ProjectPProjectIdDomainRoute
  ProjectPProjectIdGa4InsightsRoute: typeof ProjectPProjectIdGa4InsightsRoute
  ProjectPProjectIdKeywordClusteringRoute: typeof ProjectPProjectIdKeywordClusteringRoute
  ProjectPProjectIdKeywordsRoute: typeof ProjectPProjectIdKeywordsRoute
  ProjectPProjectIdLinkIntersectRoute: typeof ProjectPProjectIdLinkIntersectRoute
  ProjectPProjectIdOnPageCheckerRoute: typeof ProjectPProjectIdOnPageCheckerRoute
  ProjectPProjectIdPromptExplorerRoute: typeof ProjectPProjectIdPromptExplorerRoute
  ProjectPProjectIdRankTrackingRoute: typeof ProjectPProjectIdRankTrackingRouteWithChildren
  ProjectPProjectIdSamRoute: typeof ProjectPProjectIdSamRoute
  ProjectPProjectIdSavedRoute: typeof ProjectPProjectIdSavedRoute
  ProjectPProjectIdSearchPerformanceRoute: typeof ProjectPProjectIdSearchPerformanceRoute
  ProjectPProjectIdSerpVolatilityRoute: typeof ProjectPProjectIdSerpVolatilityRoute
  ProjectPProjectIdSettingsRoute: typeof ProjectPProjectIdSettingsRoute
  ProjectPProjectIdSitemapValidatorRoute: typeof ProjectPProjectIdSitemapValidatorRoute
  ProjectPProjectIdIndexRoute: typeof ProjectPProjectIdIndexRoute
  ProjectPProjectIdAlertsIndexRoute: typeof ProjectPProjectIdAlertsIndexRoute
  ProjectPProjectIdStrategyIndexRoute: typeof ProjectPProjectIdStrategyIndexRoute
  ProjectPProjectIdStrategyBriefsBriefIdRoute: typeof ProjectPProjectIdStrategyBriefsBriefIdRoute
}

const ProjectPProjectIdRouteRouteChildren: ProjectPProjectIdRouteRouteChildren =
  {
    ProjectPProjectIdReportsRouteRoute:
      ProjectPProjectIdReportsRouteRouteWithChildren,
    ProjectPProjectIdAuditRoute: ProjectPProjectIdAuditRouteWithChildren,
    ProjectPProjectIdBacklinksRoute: ProjectPProjectIdBacklinksRoute,
    ProjectPProjectIdBrandLookupRoute: ProjectPProjectIdBrandLookupRoute,
    ProjectPProjectIdContentGapRoute: ProjectPProjectIdContentGapRoute,
    ProjectPProjectIdCrawlBudgetRoute: ProjectPProjectIdCrawlBudgetRoute,
    ProjectPProjectIdDomainRoute: ProjectPProjectIdDomainRoute,
    ProjectPProjectIdGa4InsightsRoute: ProjectPProjectIdGa4InsightsRoute,
    ProjectPProjectIdKeywordClusteringRoute:
      ProjectPProjectIdKeywordClusteringRoute,
    ProjectPProjectIdKeywordsRoute: ProjectPProjectIdKeywordsRoute,
    ProjectPProjectIdLinkIntersectRoute: ProjectPProjectIdLinkIntersectRoute,
    ProjectPProjectIdOnPageCheckerRoute: ProjectPProjectIdOnPageCheckerRoute,
    ProjectPProjectIdPromptExplorerRoute: ProjectPProjectIdPromptExplorerRoute,
    ProjectPProjectIdRankTrackingRoute:
      ProjectPProjectIdRankTrackingRouteWithChildren,
    ProjectPProjectIdSamRoute: ProjectPProjectIdSamRoute,
    ProjectPProjectIdSavedRoute: ProjectPProjectIdSavedRoute,
    ProjectPProjectIdSearchPerformanceRoute:
      ProjectPProjectIdSearchPerformanceRoute,
    ProjectPProjectIdSerpVolatilityRoute: ProjectPProjectIdSerpVolatilityRoute,
    ProjectPProjectIdSettingsRoute: ProjectPProjectIdSettingsRoute,
    ProjectPProjectIdSitemapValidatorRoute:
      ProjectPProjectIdSitemapValidatorRoute,
    ProjectPProjectIdIndexRoute: ProjectPProjectIdIndexRoute,
    ProjectPProjectIdAlertsIndexRoute: ProjectPProjectIdAlertsIndexRoute,
    ProjectPProjectIdStrategyIndexRoute: ProjectPProjectIdStrategyIndexRoute,
    ProjectPProjectIdStrategyBriefsBriefIdRoute:
      ProjectPProjectIdStrategyBriefsBriefIdRoute,
  }

const ProjectPProjectIdRouteRouteWithChildren =
  ProjectPProjectIdRouteRoute._addFileChildren(
    ProjectPProjectIdRouteRouteChildren,
  )

interface ProjectRouteRouteChildren {
  ProjectPProjectIdRouteRoute: typeof ProjectPProjectIdRouteRouteWithChildren
}

const ProjectRouteRouteChildren: ProjectRouteRouteChildren = {
  ProjectPProjectIdRouteRoute: ProjectPProjectIdRouteRouteWithChildren,
}

const ProjectRouteRouteWithChildren = ProjectRouteRoute._addFileChildren(
  ProjectRouteRouteChildren,
)

interface AuthRouteChildren {
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAcceptInvitationRoute: typeof AuthenticatedAcceptInvitationRoute
  AuthenticatedOauthConsentRoute: typeof AuthenticatedOauthConsentRoute
  AuthenticatedSubscribeRoute: typeof AuthenticatedSubscribeRoute
  AuthenticatedOnboardingChatRoute: typeof AuthenticatedOnboardingChatRoute
  AuthenticatedOnboardingIndexRoute: typeof AuthenticatedOnboardingIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAcceptInvitationRoute: AuthenticatedAcceptInvitationRoute,
  AuthenticatedOauthConsentRoute: AuthenticatedOauthConsentRoute,
  AuthenticatedSubscribeRoute: AuthenticatedSubscribeRoute,
  AuthenticatedOnboardingChatRoute: AuthenticatedOnboardingChatRoute,
  AuthenticatedOnboardingIndexRoute: AuthenticatedOnboardingIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  ProjectRouteRoute: ProjectRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  PricingRoute: PricingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  Char91DotwellKnownChar93OpenaiAppsChallengeRoute:
    Char91DotwellKnownChar93OpenaiAppsChallengeRoute,
  ApiAiVisibilityRoute: ApiAiVisibilityRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiGa4OauthCallbackRoute: ApiGa4OauthCallbackRoute,
  ApiGscOauthCallbackRoute: ApiGscOauthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
